[book]
authors = ["Jared Wolff"]
language = "en"
multilingual = false
src = "src"
title = "Product Documentation"

[build]
# create-missing = false

[output.html.fold]
# enable = true

[output.html]
# no-section-label = true
additional-js = ["src/js/fathom.js"]
git-repository-url = "https://www.github.com/circuitdojo/docs"
